### ISSUE TITLE
[BUG] Error while extracting custom-packages.zip

### ISSUE THREAD

**Issue by yoancutillas** [Chris2011/minifierbeans#104]
**Describe the bug**
Hi, I am sorry but since the new 3.5 version, the plugin install is failing with this error: **Error while extracting** (see screenshot below)

I have tried to install it manually, I have tried (and succeed) to manually extract the custom-packages.zip folder, but when booting Netbeans, the folder is automatically deleted, and the error shows again.

**To Reproduce**
The error occurs when on Netbeans start up, and when trying to minify a file (when a file is saved in my case).

**Expected behavior**
Minifierbeans should be updated without error.

**Screenshots**
![minifierbeans-extract-error](https://github.com/Chris2011/minifierbeans/assets/9415030/bfd7ae1e-ee7c-4b5c-bb26-489afc0daf28)

**Environment (please complete the following information):**
 - OS: windows 11
 - NetBeans version: 21
 - JDK version: 21

**Comment by Chris2011** [comment]
Hi, please don't forget to update the title, [BUG] is not very helpful here. Since I investigate it I suggest you to use 3.4.0. If you figure out the problem, that would be cool. I also encountered a problem, that the extraction took veeeeeeery long. Maybe I will remove the package and just run "npm i" and hope that this is faster for most of the users. No custom logic. What do you think?

**Comment by yoancutillas** [comment]
Sorry I simply forgot the title ^^

I have tried to install 3.4 again, and encountered the same error.
I also tried with NetBeans 20 / JDK 18, same error.
That's very strange because I did install minifierbeans 3.4 on NetBeans 20 / JDK 18 / windows 11, successfully few months ago.

If extraction was the only problem, that would be fine, we can extract it manually.
But Netbeans deletes the "custom-packages" on startup and try to extract the zip file again.
Do you know how I can flag that "minifierbeans has been installed, do not try to install it again" in Netbeans config?

**Comment by Chris2011** [comment]
I think it comes from the udpate of the custom-packages maybe. NetBeans should not remove any after restart. It will check the folder and also checks the package.json from remote and from local to check the versions. It will only redownload the new package if the remote version is newer than the current local version.

I think it is better to get rid of the archive and the extraction progress and use the default behaviour just while using npm i or yarn. Manually extraction is also not an option because it is not very user friendly. It is just a workaround.

**Comment by yoancutillas** [comment]
Ok, shame on me, the "custom-packages" folder was automatically deleted only because when I extracted the zip, it was extracted in a new folder: `.netbeans/minifierbeans/custom-packages/custom-packages/`, I didn't notice it until now. Unzipping custom-packages.zip manually _does_ work. 

Extracting manually is a workaround as you said, but at least, we have one way to make it work :) 

Now, why Netbeans encounter an error while extracting the custom-packages.zip file, I don't know, I couldn't find any documentation or similar report on the web. Do you encounter the same issue on your side?

**Comment by Chris2011** [comment]
No, but I encountered the long taking task to unzip.

**Comment by yoancutillas** [comment]
Ok, so that's a config issue on my side (don't know which one unfortunately), but the long taking task issue may be connected since both issues are related to extraction.
Let me know if you need me to test something.

**Comment by Chris2011** [comment]
You can try to identify the problem. It seems that is has smth todo with google-closure-compiler. Or smth else.

**Comment by Chris2011** [comment]
So try to manipulate the archive, remove smth from it also from package.json, etc. Whatever helps. It is now try and error. You also can tell me, how long it will take when you use yarn install or npm install.

**Comment by Chris2011** [comment]
I updated the custom-packages.zip which has kjust the files inside. The path needs to be .netbeasn/minifierbeans/custom-packages/*.*. Please test it.

**Comment by jshster** [comment]
Apologies for the duplicate issue I created yesterday.  Because it mentioned CLI error I thought it was different.   Just like to add that extracting the custom-packages.zip into the .netbeans/miniferbeans/ folder worked for me too.  Thanks.

**Comment by Chris2011** [comment]
@yoancutillas just lemme know whether that worked or we still need the workaround.

**Comment by SolracLeinad** [comment]
I'm using Debian and I had to unzip custom-packages.zip file to `~/.netbeans/minifierbeans/custom-packages/` but I additionally had to  `sed -i -e 's/\r$//' ~/.netbeans/minifierbeans/custom-packages/google-closure-compiler ` because I was getting the `google-closure-compiler: bad interpreter: /bin/sh^M` error.

It's working now.

**Comment by Chris2011** [comment]
So all in all, the first problem was, that I zipped the archive with a wrong compression strength. I just used windows zipping, before I used 7z with highest compression strength (9 - Ultra). The second problem was, that I removed the custom-packages folder from the zip and added the files to the root path which is wrong.

This is fixed in custom-packages 1.5.2 and it should work now out of the box, after opening NetBeans. If not, please empty the folder .netbeans/minifierbeans and restart NetBeans.

With Minifierbeans 3.5.1 I also increased the performance of extracting the archive.

**Comment by yoancutillas** [comment]
Sorry I couldn't make the tests last week, but I confirm now that everything is working properly, thank you for your work.
