### ISSUE TITLE
Configuration / Settings missing

### ISSUE THREAD

**Issue by kjf3006** [Chris2011/minifierbeans#54]
I moved from Netbeans 8.2 to Netbeans 11.1, installed the Plugin, but the "JS CSS Minify Compress" option is missing in Preferences-Screen.

<img width="883" alt="Bildschirmfoto 2019-08-30 um 17 50 24" src="https://user-images.githubusercontent.com/27950262/64034521-21b6e500-cb4f-11e9-85f1-7c3c69eb7796.png">

And somehow the Plugin is now just called "user installed plugins"

<img width="892" alt="Bildschirmfoto 2019-08-30 um 17 54 19" src="https://user-images.githubusercontent.com/27950262/64034609-4ad77580-cb4f-11e9-8132-20af29c07b50.png">

Minifying per se is working!

**Comment by Chris2011** [comment]
> option is missing in Preferences-Screen.

Unfortunately I forgot to update the screenshots. You can find the minified stuff unter options -> htm/js which makes much more sense, because it is for the web technologies for HTML, CSS, JS, JSON etc.

> And somehow the Plugin is now just called "user installed plugins"

What you see are the grouped categories. All 3rd party plugins are under "User installed Plugins". So there is a checkbox called "Show details". If you click it, you will see all plugins for the different categories.
