### ISSUE TITLE
After reboot Netbeans reset "Minify on save" setting

### ISSUE THREAD

**Issue by JuergenLaas** [Chris2011/minifierbeans#85]
Hello it’s me again,

after new installation of Windows 10. Minifierbeans 3.3.1 resetted setting “Minify on save”.
After start of Netbeans i check “Minify on save” again to activate minifierbeans.
I use Netbeans 12.4, OpenJ9 9-0.26.0, NodeJS 14.17.3 and minifierbeans 3.3.1

Best regards 

Jürgen

**Comment by Chris2011** [comment]
Hey @JuergenLaas thx for the info. I think this is related to issue #73. But what are your steps? I think after new installation Win 10 and a fresh new installation of NetBeans and minifierbeans it is quite normal to have a resettet option. Or what did you do? Please be more specific in your tickets.

I understand your scenario as follow:
* You installed windows 10
* You installed NetBeans 12.4
* You installed Minifierbeans 3.3.1

So here it seems normal to not have any settings at all, because it is just new. If the steps are not correct please let me know, what you did.

**Comment by Chris2011** [comment]
If you just say about after reboot netbeans, what your title is saying, then it is just the same as #73 that the persistance is not working. Sry for that, maybe I've broken smth.

**Comment by Chris2011** [comment]
I'm working on it, but it will take some time. I will change a lot of code, make it easier as it is now.

**Comment by JuergenLaas** [comment]
Sorry, I was unavailable. Yes, your order is correct. First I installed Windows 10, then Java (adoptopenjdk.net) OpenJ9 and then Netbeans 12.4 with your plugin. I don't get an error message. The only thing that occurred to me is that when I activate "minify on save". The "Apply" button does not light up.

**Comment by Chris2011** [comment]
Yes, this is the problem atm. I'm refactoring the code, the whole code :D and hope that this will fix the problem.

**Comment by DucMinh19** [comment]
I had a same issue. I will fix options in your source and re-build while waiting for new version.

**Comment by Chris2011** [comment]
Done in release 3.4.0: https://github.com/Chris2011/minifierbeans/releases/tag/3.4.0
